apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wm-pv-claim
  namespace: wm-is-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
